version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./:/app

  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
  myphpmyadmin:
    image: phpmyadmin:5.1.1-fpm-alpine
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysqldb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=p@ssw0rd1
  redis:
    image: redis:latest
    restart: always
    ports:
    - 6380:6379
  st-agent:
    image: sematext/agent:latest
    environment:
      - INFRA_TOKEN=381660b9-9ddb-4466-a90e-22040aaf2378
      - REGION=EU
    cap_add:
      - SYS_ADMIN
    restart: always
    volumes:
      - /:/hostfs:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /var/run/:/var/run
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys:/host/sys:ro
      - /dev:/hostfs/dev:ro

volumes:
  mysql:
  mysql_config: